### ISSUE TITLE
Jupiter migration - ensure all items have a date

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/metadata#130]
In Jupiter all items will need to have a date, dcterms:created for non-thesis items, ual:graduationDate for thesis items.

- [ ] draft report(s) on (and proposed courses of action for addressing) current status of dates in ERA for stakeholder review

**Comment by sfarnel** [comment]
@leahvanderjagt [here](https://docs.google.com/a/ualberta.ca/spreadsheets/d/1Sa1ol6tKmWD_NHuySZ2mYwavH-cJG6eeQqlgtZGxXkc/edit?usp=sharing) is a report of the current status of dates in ERA.
- the first tab lists non-thesis items with no dcterms:created
- the second tab lists thesis items with no ual:graduationDate

Each tab has comments on proposed courses of action for populating the appropriate date. These should be quite strightforward and many can be addressed in large batches. Happy to meet to review. Thanks @danydvd for generating these

**Comment by zschoenb** [comment]
@danydvd @sfarnel is all this date work complete?

**Comment by sfarnel** [comment]
some dates have been fixed in current era and others will be as part of migration script. would be great to run another report after latest migration

**Comment by danydvd** [comment]
Here is a [report](https://docs.google.com/spreadsheets/d/18aXeQK3qnACeOlHHtzmmVlKRx0y-qPYTbnnCm_8Es3g/edit#gid=725876574) of dates using data from migration package. There are still 1526 items without ualdate:sortyear. 
- [655](https://docs.google.com/spreadsheets/d/18aXeQK3qnACeOlHHtzmmVlKRx0y-qPYTbnnCm_8Es3g/edit#gid=1918793025) items without date, also doesn't have a type and most of them are private items. 
- [866](https://docs.google.com/spreadsheets/d/18aXeQK3qnACeOlHHtzmmVlKRx0y-qPYTbnnCm_8Es3g/edit#gid=725876574) items without dates that are sorted by their dcterm:type (orphan items that does not belong to any collection are also included. e.g. draft-submitted)
   1. 197 Articles
   2. 16 Books
   3. 9 Book Chapters
   4. 363 Images
   5. 43 Learning Objects
   6. 115 Research Materials
   7. 67 Conference Posters
   8. 50 Datasets
   9. 6 Reviews 

- there is only [one](https://docs.google.com/spreadsheets/d/18aXeQK3qnACeOlHHtzmmVlKRx0y-qPYTbnnCm_8Es3g/edit#gid=0) Thesis without ual:graduationDate. 

**NOTE:** this reports does not include items that a date was added to by ERA help desk. Items from "Schaefer, Otto" collection are also included.

@sfarnel can we discuss the final items types that has to be migrated so that I can generate a list excluding unwanted items

**Comment by danydvd** [comment]
The issue is resolved
