### ISSUE TITLE
Spike: Digitized legacy theses: Scrape Abstract from IA

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/metadata#328]
Investigate possibility of pulling the abstract for theses from one of the formats available via IA

**Comment by danydvd** [comment]
The script downloads the .txt file for every records that it creates triple for. In order to pull abstract from the text file, the script should be able to identify the boundaries of the abstract text (where the abstract starts and ends). Records in the collection do not follow a single pattern for identifying the abstract; it is sometimes called "Abstract" and sometimes "Introduction".

**Comment by danydvd** [comment]
Work will continue in #327
