### ISSUE TITLE
Explore duplicate merging of finding aids

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/metadata#379]
The UA Archives has numerous finding aids that have multiple and slightly different versions. These need to be merged into a single finding aid that can then be reviewed and cleaned. Attached are two samples in both csv and xml: 
Barter Theatre has 3 finding aids that need to be merged but there isn't a lot of info there. 
Alexander Cameron Rutherford has 2 that need merging but there are a LOT of child records nested at different levels.
Explore possibilities for merging.
[eadsandcsvsforduplicatemerging.zip](https://github.com/ualbertalib/metadata/files/2241422/eadsandcsvsforduplicatemerging.zip)

**Comment by anayram** [comment]
Because of the way csvs are exported from Atom, problems come up when interpreting the nested records. E.g. the full fond title (e.g. "Barter Theatre Fonds") is interpreted at the same level than a series title (e.g. "Programs, Publicity and Press"). So it will be easy to introduce errors while merging given that hierarchies are not clear.

Merging xml seems like the best option although it has its own disadvantages like lots of repetition and unnecessary merges (often due to differences order of metadata nodes).

Either way (merging csv or xml), this work would involve human cleanup so, a third option would be to use a visual comparison tool that allows to visualize (and to focus on) specific xml sections with that have different content.

**Comment by anayram** [comment]
We'll set up meeting with Kirsta to go over options.
