### ISSUE TITLE
CanLink: Records from Queen's University listed as being published by Tunis University 

### ISSUE THREAD

**Issue by a-cohen** [ualbertalib/metadata#422]
MARC records from Queen's University list [Publisher not identified] in the 264 $b field. In CanLink they're listed as dbpedia:Tunis University under the dct:publisher and http://id.loc.gov/vocabulary/relators/pub predicates. This seems to be the case for all records from Queen's.

Example record [http://canlink.library.ualberta.ca/thesis/910e88b07addbb822f4582a5d2407d38](http://canlink.library.ualberta.ca/thesis/910e88b07addbb822f4582a5d2407d38)

**Comment by danydvd** [comment]
**The issue:**

The processing script use difflib to match University name (pulled from MARC) with a list of universities pulled from DBpedia. The default cutoff was 0.6 and it matched "Queen's University" to "Tunis University" and matched "Queen's University at Kingston (Ont)" to "Queen's University at Kingston" (correct match). 

Setting the cutoff to higher value (e.g. 0.95) won't match anything and no University URI will be returned (a github issue will be created and a URI has to be added manually). We can set constraint in the code for known issues to map to the proper URI. However, this won't fixed unknown (future) problems.

List of thesis with this issue is [here](https://docs.google.com/spreadsheets/d/1fSpV1gX_AInoOTTcEeUYunh0gSd9TXn16Zbu_js-2Ek/edit?ts=5d090c96#gid=847318930). Thanks @a-cohen 

**Solution:**

Pull all Canadian universities form DBpedia and create a pickle to be used for matching. Use properties like `rdfs:label` and `foaf:name` for redundancy in matching process

**Comment by danydvd** [comment]
**Update:**

A list of all the Canadian universities was pulled from DBpedia in this form:
`{rdfs:label: [DBpedia URI, Wikidata URI]}`

The DBpedia and Wikidata URIs will added as `owl:sameAs` to the `dcterms:Publisher` object.

The difflib matching level is increased to 80% for better accuracy. However, this will not match something like this:
`Memorial University of Newfoundland` and `Memorial University`

A fuzzy matching function was used to resolve this (This function is a bit more computationally intensive so it was used only if the difflib did not find any match).

**Comment by sfarnel** [comment]
Thanks @danydvd great news on this; should help a great deal!

**Comment by danydvd** [comment]
Script modification is finished. Queen's University and Memorial University of Newfoundland will be correctly mapped once a full re-processing is preformed. 

Closing for now.
